[package]
name = "model"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { workspace = true }
derive_builder = "0.12.0"
sqlx = { workspace = true }
